Adding ppc64-diag and automating builds
osuosl/bento pull request #27
Opened 2017-06-09 23:11 UTC by hodgesto

2017-06-12 18:29 UTC, ramereth requested changes
Why are you using filenames with ``WIP`` in them? I'd assume if you're intending on merging this, you should give them a proper name without ``WIP`` in them. Also, please make sure you any comments I suggested on one packer template gets changed on the others as well.

2017-06-12 18:29 UTC, ramereth commented on build.sh
> +done
How is this different than ``scripts/build-image.sh``?

2017-06-12 18:29 UTC, ramereth commented on packer/centos-7.2-ppc64-openstack.json
> +      "disk_size": 4096,
Why the increase? Couldn't you just make this 3G instead of moving up to 4G? We would need to update our m1.tiny definition if we did that.

2017-06-12 18:29 UTC, ramereth commented on packer/centos-7.2-ppc64-openstack.json
> +	"scripts/centos/ppc64.sh",
Please check the indentation, seems off.

2017-06-12 18:29 UTC, ramereth commented on packer/scripts/centos/ppc64.sh
> +yum update -y
Please do not run this, it's handled in other places and not required for this.

2017-06-12 18:29 UTC, ramereth commented on packer/scripts/centos/ppc64.sh
> +yum install -y ppc64-diag
I would just move this to the ``openstack.sh`` script and only install it if ``uname -m `` is either ``ppc64`` or ``ppc64le``.

2017-06-16 18:41 UTC, hodgesto commented on build.sh
> +done
We want to run all of the packer images. If I'm not mistaken this only runs 1? but I will use this in the future.

2017-06-16 18:41 UTC, hodgesto commented on packer/centos-7.2-ppc64-openstack.json
> +      "disk_size": 4096,
Undone, was just testing

2017-06-16 18:54 UTC, ramereth commented on build.sh
> +done
I think we should sit down and discuss this more. I'm not sure this is the right approach.

2017-06-16 19:49 UTC, hodgesto commented on build.sh
> +done
Okay. my ride back home leaves soon as I just found out so I have to be OoO until monday, but I will work on the other tasks at hand until then.

2017-06-26 16:21 UTC, closed without merging