hodgesto/update centos images
osuosl/bento pull request #29
Opened 2017-06-26 16:22 UTC by hodgesto

Added CentOS 7.2 BE

2017-06-26 17:05 UTC, hodgesto commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update Packer images for ppc64](https://trello.com/c/HsLFd74K/400-update-packer-images-for-ppc64)

2017-06-26 17:39 UTC, hodgesto commented
Working images on openpower-controller:
- [x] CentOS 7.3 BE
- [x] CentOS 7.3 LE
- [x] CentOS 7.2 BE

2017-06-26 17:45 UTC, knightsamar commented
Is CentOs 7.2 LE also included?

2017-06-26 17:48 UTC, knightsamar commented
@hodgesto Are these images tested using openstack_taster? 
We will get to automating it using Jenkins but for now, we have to run it manually against the uploaded image.

2017-06-26 17:48 UTC, hodgesto commented
@knightsamar CentOS 7.2 LE's iso is not available on centos-altarch.osuosl.org

2017-06-26 17:49 UTC, hodgesto commented
@knightsamar and no, but I will do that.

2017-06-26 17:56 UTC, ramereth commented
Let's not worry about 7.2 anymore.

2017-06-26 17:57 UTC, knightsamar commented
Yeah looks like they removed that from everywhere. Weird that BE is present but LE isn't for 7.2

2017-06-26 18:24 UTC, hodgesto commented
Working and Tasted images on openpower-controller:
- [ ] CentOS 7.2 BE
- [ ] CentOS 7.3 LE
- [ ] CentOS 7.3 BE

2017-06-26 18:46 UTC, knightsamar commented
@hodgesto once you have tested things, please also pastebin the openstack_taster results for each image so we can have a look.

2017-06-26 18:47 UTC, hodgesto commented
CentOS 7.2 BE taste results:

https://pastebin.osuosl.org/57726/

2017-06-26 18:49 UTC, knightsamar commented
@hodgesto looks good. please run the `volume` test suite too!

2017-06-26 19:01 UTC, hodgesto commented
will run the volume suite on these after I partition the volume

2017-06-26 19:22 UTC, hodgesto commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update Packer images for ppc64](https://trello.com/c/HsLFd74K/400-update-packer-images-for-ppc64)

2017-06-26 20:27 UTC, ramereth requested changes

2017-06-26 20:27 UTC, ramereth commented on packer/scripts/centos/openstack.sh
> +yum -y install $packages
I would just move this command directly into the if block above instead of using a variable for it.

2017-06-26 20:27 UTC, ramereth commented on packer/ubuntu-14.04-ppc64.json
> -}
Why is this being removed in this PR?

2017-06-26 20:27 UTC, ramereth commented on scripts/build-image.sh
> +qemu-img convert -o compat=0.10 -O qcow2 -c ${DIR_NAME}/${IMAGE_NAME} \
Why is this change needed?

2017-06-27 06:06 UTC, knightsamar commented
@hodgesto the volume results for CentOS 7.2 BE are missing.

Also were you able to *manually* mount the two volumes `new-test-volume` and `volume-testing_a` from any instance?

2017-06-27 17:54 UTC, hodgesto commented on scripts/build-image.sh
> +qemu-img convert -o compat=0.10 -O qcow2 -c ${DIR_NAME}/${IMAGE_NAME} \
Packer builds a qcow2 image, but .qcow2 is not appended to any of the files it creates.

2017-06-27 17:55 UTC, hodgesto commented
@knightsamar No, based on `fdisk -l` on openpower3 I don't think that they are partitioned.

2017-06-27 17:57 UTC, hodgesto commented on packer/ubuntu-14.04-ppc64.json
> -}
I thought this was one of the files I created... Looks like it wasn't. I'll put that back :) sorry.

2017-06-27 19:04 UTC, knightsamar commented
@hodgesto and are those two volumes not detected as devices on a instance, when you attach them  ?

2017-06-28 17:13 UTC, hodgesto commented
@knightsamar so I was in fact able to mount them manually, I don't know why I could not initially but there were some issues with that instance I believe. I couldn't ssh into it either. But yes, they are manually attachable and show up in /dev

2017-06-28 18:50 UTC, hodgesto commented
CentOS OpenStack Taster results: 
- [x] CentOS 7.2 BE - 
- [ ] CentOS 7.3 BE - 
- [ ] CentOS 7.3 LE -

2017-06-28 19:21 UTC, hodgesto commented
@knightsamar @ramereth ready for review

2017-06-28 20:28 UTC, knightsamar approved these changes
@hodgesto why are we removing `packer/fedora-23-ppc64-openstack.json` in this PR ?  :)
I think you were working on two different branches and the changes "crossed over". 

We should have you use fish's better shell prompt maybe ;)

BTW, we need you to deploy these out carefully, after @ramereth's review. I would suggest that you rename and make private the old images instead of deleting them and then make public the new images by renaming them.

2017-06-28 20:29 UTC, knightsamar requested changes
Oops, please discard the fedora json file from the PR first.

2017-06-29 17:06 UTC, hodgesto commented
@knightsamar everything should be right... Which image are you talking about? The packer/fedora-23-ppc64-openstack.json is no longer in here.

2017-06-29 18:30 UTC, knightsamar commented
So, we have a symlink called CentOS 7.2 LE pointing at CentOS 7.3 LE in this PR. Is that ok, @ramereth ?

2017-06-29 18:33 UTC, hodgesto commented
@knightsamar That should not be in there. 7.2 LE image does not exist. I'll see if I can get it out.

2017-06-29 18:47 UTC, ramereth commented on scripts/build-image.sh
> +qemu-img convert -o compat=0.10 -O qcow2 -c ${DIR_NAME}/${IMAGE_NAME} \
What version of packer are you using for this? I wonder if this is a difference between running it on x86 vs. ppc64le or something else is going on. I know this change will break x86 builds.

2017-06-29 18:48 UTC, ramereth commented
@knightsamar that's not a symlink, that's showing that the file was renamed and updated.

2017-06-29 19:00 UTC, hodgesto commented on scripts/build-image.sh
> +qemu-img convert -o compat=0.10 -O qcow2 -c ${DIR_NAME}/${IMAGE_NAME} \
hm. I'm using packer 0.8.6.

2017-06-29 19:04 UTC, ramereth commented on scripts/build-image.sh
> +qemu-img convert -o compat=0.10 -O qcow2 -c ${DIR_NAME}/${IMAGE_NAME} \
I suspect this is an issue with the version of packer. We're using a horribly outdated version but I'd rather we wait to deal with the upgrade path later. How about you set this change based on what version of packer is being executed (Can be seen running ``packer version``)? If we're running 0.7.5 then we need the .qcow2 extension, if we're running anything else let's assume we don't need it for now.

2017-06-29 19:05 UTC, hodgesto commented on scripts/build-image.sh
> +qemu-img convert -o compat=0.10 -O qcow2 -c ${DIR_NAME}/${IMAGE_NAME} \
I can make it do this only for ppc64 builds if that would work, and keep the .qcow2 for other archs.

2017-06-29 19:05 UTC, hodgesto commented on scripts/build-image.sh
> +qemu-img convert -o compat=0.10 -O qcow2 -c ${DIR_NAME}/${IMAGE_NAME} \
Ok! I will do that. Thanks much.

2017-06-29 19:23 UTC, hodgesto commented
@ramereth @knightsamar Should be good.

2017-06-29 19:31 UTC, knightsamar approved these changes

2017-06-29 21:15 UTC, ramereth commented on scripts/build-image.sh
> +if [ $(packer -v) == "0.7.5" ] ; then
You need to change this to the following:

``` bash
if [ "$(packer version | grep ^Packer)" == "Packer v0.7.5" ] ; then
```

It needs to look at the EXACT string. Plus you need to put quotes around the command.

2017-06-29 21:48 UTC, hodgesto commented on scripts/build-image.sh
> +if [ $(packer -v) == "0.7.5" ] ; then
got it. I see

2017-06-29 22:00 UTC, ramereth approved these changes

2017-06-30 20:22 UTC, merged